package com.moongchijang.domain.store.domain.entity

enum class StoreRecommendationRegionType(
    val region: RegionType,
    val label: String,
) {
    SEOUL_GANGNAM(RegionType.SEOUL, "강남"),
    SEOUL_YEOKSAM(RegionType.SEOUL, "역삼"),
    SEOUL_SAMSEONG(RegionType.SEOUL, "삼성"),
    SEOUL_SINSA(RegionType.SEOUL, "신사"),
    SEOUL_APGUJEONG(RegionType.SEOUL, "압구정"),
    SEOUL_CHEONGDAM(RegionType.SEOUL, "청담"),
    SEOUL_SEOCHO(RegionType.SEOUL, "서초"),
    SEOUL_BANGBAE(RegionType.SEOUL, "방배"),
    SEOUL_GYODAE(RegionType.SEOUL, "교대"),
    SEOUL_JAMSIL(RegionType.SEOUL, "잠실"),
    SEOUL_SINCHEON(RegionType.SEOUL, "신천"),
    SEOUL_SONGPA(RegionType.SEOUL, "송파"),
    SEOUL_JONGNO(RegionType.SEOUL, "종로"),
    SEOUL_JUNGGU(RegionType.SEOUL, "중구"),
    SEOUL_EULJIRO(RegionType.SEOUL, "을지로"),
    SEOUL_MYEONGDONG(RegionType.SEOUL, "명동"),
    SEOUL_HONGDAE(RegionType.SEOUL, "홍대"),
    SEOUL_HAPJEONG(RegionType.SEOUL, "합정"),
    SEOUL_SANGSU(RegionType.SEOUL, "상수"),
    SEOUL_MAPO(RegionType.SEOUL, "마포"),
    SEOUL_SEONGSU(RegionType.SEOUL, "성수"),
    SEOUL_GEONDAE(RegionType.SEOUL, "건대"),
    SEOUL_GWANGJIN(RegionType.SEOUL, "광진"),
    SEOUL_ITAEWON(RegionType.SEOUL, "이태원"),
    SEOUL_HANNAM(RegionType.SEOUL, "한남"),
    SEOUL_YONGSAN(RegionType.SEOUL, "용산"),
    SEOUL_YEONGDEUNGPO(RegionType.SEOUL, "영등포"),
    SEOUL_YEOUIDO(RegionType.SEOUL, "여의도"),
    SEOUL_NOWON(RegionType.SEOUL, "노원"),
    SEOUL_DOBONG(RegionType.SEOUL, "도봉"),
    SEOUL_GANGBUK(RegionType.SEOUL, "강북"),

    GYEONGGI_SUWON(RegionType.GYEONGGI, "수원"),
    GYEONGGI_YEONGTONG(RegionType.GYEONGGI, "영통"),
    GYEONGGI_PALDAL(RegionType.GYEONGGI, "팔달"),
    GYEONGGI_SEONGNAM(RegionType.GYEONGGI, "성남"),
    GYEONGGI_BUNDANG(RegionType.GYEONGGI, "분당"),
    GYEONGGI_PANGYO(RegionType.GYEONGGI, "판교"),
    GYEONGGI_GOYANG(RegionType.GYEONGGI, "고양"),
    GYEONGGI_ILSAN(RegionType.GYEONGGI, "일산"),
    GYEONGGI_YONGIN(RegionType.GYEONGGI, "용인"),
    GYEONGGI_SUJI(RegionType.GYEONGGI, "수지"),
    GYEONGGI_GIHEUNG(RegionType.GYEONGGI, "기흥"),
    GYEONGGI_BUCHEON(RegionType.GYEONGGI, "부천"),
    GYEONGGI_JUNGDONG(RegionType.GYEONGGI, "중동"),
    GYEONGGI_SANGDONG(RegionType.GYEONGGI, "상동"),
    GYEONGGI_ANSAN(RegionType.GYEONGGI, "안산"),
    GYEONGGI_DANWON(RegionType.GYEONGGI, "단원"),
    GYEONGGI_SANGROK(RegionType.GYEONGGI, "상록"),
    GYEONGGI_NAMYANGJU(RegionType.GYEONGGI, "남양주"),
    GYEONGGI_DASAN(RegionType.GYEONGGI, "다산"),
    GYEONGGI_BYEOLNAE(RegionType.GYEONGGI, "별내"),
    GYEONGGI_ANYANG(RegionType.GYEONGGI, "안양"),
    GYEONGGI_PYEONGCHON(RegionType.GYEONGGI, "평촌"),
    GYEONGGI_BEOMGYE(RegionType.GYEONGGI, "범계"),
    GYEONGGI_HWASEONG(RegionType.GYEONGGI, "화성"),
    GYEONGGI_DONGTAN(RegionType.GYEONGGI, "동탄"),
    GYEONGGI_PAJU(RegionType.GYEONGGI, "파주"),
    GYEONGGI_UNJEONG(RegionType.GYEONGGI, "운정"),

    INCHEON_SONGDO(RegionType.INCHEON, "송도"),
    INCHEON_YEONSU(RegionType.INCHEON, "연수"),
    INCHEON_GUWOL(RegionType.INCHEON, "구월"),
    INCHEON_NAMDONG(RegionType.INCHEON, "남동"),
    INCHEON_BUPYEONG(RegionType.INCHEON, "부평"),
    INCHEON_GYEYANG(RegionType.INCHEON, "계양"),
    INCHEON_CHEONGNA(RegionType.INCHEON, "청라"),
    INCHEON_SEOGU(RegionType.INCHEON, "서구"),
    INCHEON_JUAN(RegionType.INCHEON, "주안"),
    INCHEON_MICHUHOL(RegionType.INCHEON, "미추홀"),
    INCHEON_YEONGJONGDO(RegionType.INCHEON, "영종도"),
    INCHEON_JUNGGU(RegionType.INCHEON, "중구"),

    GANGWON_CHUNCHEON(RegionType.GANGWON, "춘천"),
    GANGWON_WONJU(RegionType.GANGWON, "원주"),
    GANGWON_GANGNEUNG(RegionType.GANGWON, "강릉"),
    GANGWON_SOKCHO(RegionType.GANGWON, "속초"),
    GANGWON_YANGYANG(RegionType.GANGWON, "양양"),
    GANGWON_DONGHAE(RegionType.GANGWON, "동해"),
    GANGWON_SAMCHEOK(RegionType.GANGWON, "삼척"),

    DAEJEON_DUNSAN(RegionType.DAEJEON, "둔산"),
    DAEJEON_SEOGU(RegionType.DAEJEON, "서구"),
    DAEJEON_EUNHAENG(RegionType.DAEJEON, "은행"),
    DAEJEON_DAEHEUNG(RegionType.DAEJEON, "대흥"),
    DAEJEON_JUNGGU(RegionType.DAEJEON, "중구"),
    DAEJEON_YUSEONG(RegionType.DAEJEON, "유성"),
    DAEJEON_DOAN(RegionType.DAEJEON, "도안"),
    DAEJEON_DONGGU(RegionType.DAEJEON, "동구"),
    DAEJEON_DAEDEOK(RegionType.DAEJEON, "대덕"),

    SEJONG_SEJONG(RegionType.SEJONG, "세종"),

    CHUNGNAM_CHEONAN(RegionType.CHUNGNAM, "천안"),
    CHUNGNAM_SINBU(RegionType.CHUNGNAM, "신부"),
    CHUNGNAM_DUJEONG(RegionType.CHUNGNAM, "두정"),
    CHUNGNAM_ASAN(RegionType.CHUNGNAM, "아산"),
    CHUNGNAM_TANGJEONG(RegionType.CHUNGNAM, "탕정"),
    CHUNGNAM_DANGJIN(RegionType.CHUNGNAM, "당진"),
    CHUNGNAM_SEOSAN(RegionType.CHUNGNAM, "서산"),
    CHUNGNAM_GYERYONG(RegionType.CHUNGNAM, "계룡"),
    CHUNGNAM_NONSAN(RegionType.CHUNGNAM, "논산"),

    CHUNGBUK_CHEONGJU(RegionType.CHUNGBUK, "청주"),
    CHUNGBUK_SANGDANG(RegionType.CHUNGBUK, "상당"),
    CHUNGBUK_HEUNGDEOK(RegionType.CHUNGBUK, "흥덕"),
    CHUNGBUK_CHUNGJU(RegionType.CHUNGBUK, "충주"),
    CHUNGBUK_JECHEON(RegionType.CHUNGBUK, "제천"),
    CHUNGBUK_EUMSEONG(RegionType.CHUNGBUK, "음성"),
    CHUNGBUK_JINCHEON(RegionType.CHUNGBUK, "진천"),

    BUSAN_SEOMYEON(RegionType.BUSAN, "서면"),
    BUSAN_JEONPO(RegionType.BUSAN, "전포"),
    BUSAN_JINGU(RegionType.BUSAN, "진구"),
    BUSAN_HAEUNDAE(RegionType.BUSAN, "해운대"),
    BUSAN_CENTUM(RegionType.BUSAN, "센텀"),
    BUSAN_MARINE_CITY(RegionType.BUSAN, "마린시티"),
    BUSAN_GWANGALLI(RegionType.BUSAN, "광안리"),
    BUSAN_SUYEONG(RegionType.BUSAN, "수영"),
    BUSAN_NAMCHEON(RegionType.BUSAN, "남천"),
    BUSAN_NAMPO(RegionType.BUSAN, "남포"),
    BUSAN_JUNGGU(RegionType.BUSAN, "중구"),
    BUSAN_YEONGDO(RegionType.BUSAN, "영도"),
    BUSAN_DONGRAE(RegionType.BUSAN, "동래"),
    BUSAN_YEONSAN(RegionType.BUSAN, "연산"),
    BUSAN_BUSANDAE(RegionType.BUSAN, "부산대"),
    BUSAN_SAHA(RegionType.BUSAN, "사하"),
    BUSAN_HADAN(RegionType.BUSAN, "하단"),

    ULSAN_SAMSAN(RegionType.ULSAN, "삼산"),
    ULSAN_DALDONG(RegionType.ULSAN, "달동"),
    ULSAN_NAMGU(RegionType.ULSAN, "남구"),
    ULSAN_SEONGNAM(RegionType.ULSAN, "성남"),
    ULSAN_JUNGGU(RegionType.ULSAN, "중구"),
    ULSAN_DONGGU(RegionType.ULSAN, "동구"),
    ULSAN_BUKGU(RegionType.ULSAN, "북구"),
    ULSAN_ULJU(RegionType.ULSAN, "울주"),

    GYEONGNAM_CHANGWON(RegionType.GYEONGNAM, "창원"),
    GYEONGNAM_SANGNAM(RegionType.GYEONGNAM, "상남"),
    GYEONGNAM_UICHANG(RegionType.GYEONGNAM, "의창"),
    GYEONGNAM_GIMHAE(RegionType.GYEONGNAM, "김해"),
    GYEONGNAM_YANGSAN(RegionType.GYEONGNAM, "양산"),
    GYEONGNAM_JINJU(RegionType.GYEONGNAM, "진주"),
    GYEONGNAM_GEOJE(RegionType.GYEONGNAM, "거제"),
    GYEONGNAM_TONGYEONG(RegionType.GYEONGNAM, "통영"),

    GYEONGBUK_POHANG(RegionType.GYEONGBUK, "포항"),
    GYEONGBUK_GYEONGJU(RegionType.GYEONGBUK, "경주"),
    GYEONGBUK_HWANGRIDAN_GIL(RegionType.GYEONGBUK, "황리단길"),
    GYEONGBUK_GUMI(RegionType.GYEONGBUK, "구미"),
    GYEONGBUK_GYEONGSAN(RegionType.GYEONGBUK, "경산"),
    GYEONGBUK_ANDONG(RegionType.GYEONGBUK, "안동"),

    DAEGU_DONGSEONGNO(RegionType.DAEGU, "동성로"),
    DAEGU_JUNGGU(RegionType.DAEGU, "중구"),
    DAEGU_SUSEONGGU(RegionType.DAEGU, "수성구"),
    DAEGU_BEOMEO(RegionType.DAEGU, "범어"),
    DAEGU_SANGIN(RegionType.DAEGU, "상인"),
    DAEGU_DALSEO(RegionType.DAEGU, "달서"),
    DAEGU_CHILGOK(RegionType.DAEGU, "칠곡"),
    DAEGU_BUKGU(RegionType.DAEGU, "북구"),
    DAEGU_DONGGU(RegionType.DAEGU, "동구"),

    GWANGJU_SANGMU_JIGU(RegionType.GWANGJU, "상무지구"),
    GWANGJU_CHIPYEONG(RegionType.GWANGJU, "치평"),
    GWANGJU_SEOGU(RegionType.GWANGJU, "서구"),
    GWANGJU_DONGMYEONGDONG(RegionType.GWANGJU, "동명동"),
    GWANGJU_CHUNGJANGRO(RegionType.GWANGJU, "충장로"),
    GWANGJU_DONGGU(RegionType.GWANGJU, "동구"),
    GWANGJU_SUWAN(RegionType.GWANGJU, "수완"),
    GWANGJU_CHEOMDAN(RegionType.GWANGJU, "첨단"),
    GWANGJU_GWANGSANGU(RegionType.GWANGJU, "광산구"),
    GWANGJU_BONGSEON(RegionType.GWANGJU, "봉선"),
    GWANGJU_NAMGU(RegionType.GWANGJU, "남구"),
    GWANGJU_BUKGU(RegionType.GWANGJU, "북구"),

    JEONNAM_YEOSU(RegionType.JEONNAM, "여수"),
    JEONNAM_SUNCHEON(RegionType.JEONNAM, "순천"),
    JEONNAM_MOKPO(RegionType.JEONNAM, "목포"),
    JEONNAM_NAMAK(RegionType.JEONNAM, "남악"),
    JEONNAM_NAJU(RegionType.JEONNAM, "나주"),

    JEONBUK_JEONJU(RegionType.JEONBUK, "전주"),
    JEONBUK_GAEKRIDANGIL(RegionType.JEONBUK, "객리단길"),
    JEONBUK_WANSAN(RegionType.JEONBUK, "완산"),
    JEONBUK_IKSAN(RegionType.JEONBUK, "익산"),
    JEONBUK_GUNSAN(RegionType.JEONBUK, "군산"),

    JEJU_JEJU_SI(RegionType.JEJU, "제주시"),
    JEJU_AEWOL(RegionType.JEJU, "애월"),
    JEJU_HALLIM(RegionType.JEJU, "한림"),
    JEJU_JOCHEON(RegionType.JEJU, "조천"),
    JEJU_GUJWA(RegionType.JEJU, "구좌"),
    JEJU_SEOGWIPO_SI(RegionType.JEJU, "서귀포시"),
    JEJU_JUNGMUN(RegionType.JEJU, "중문"),
    JEJU_ANDEOK(RegionType.JEJU, "안덕"),
    JEJU_SEONGSAN(RegionType.JEJU, "성산"),
    JEJU_PYOSEON(RegionType.JEJU, "표선");
}
