spring.application.name=moongchijang

spring.profiles.active=local

# Swagger / SpringDoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.url=/openapi.yaml
