services:
  app-dev:
    image: ${ECR_REPOSITORY_URL}:develop
    container_name: moongchijang-dev
    env_file:
      - ../.env.dev
    restart: unless-stopped

  app-prod:
    image: ${ECR_REPOSITORY_URL}:main
    container_name: moongchijang-prod
    env_file:
      - ../.env.prod
    restart: unless-stopped

  nginx:
    image: nginx:1.29-alpine
    container_name: moongchijang-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
