global:
  resolve_timeout: 5m

route:
  receiver: "null"
  group_by: ["alertname", "service", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - receiver: payment-discord
      matchers:
        - env="__ALERT_ENV__"
        - domain="payment"
    - receiver: monitoring-critical-discord
      matchers:
        - env="__ALERT_ENV__"
        - severity="critical"
    - receiver: monitoring-warning-discord
      matchers:
        - env="__ALERT_ENV__"
        - severity="warning"

receivers:
  - name: "null"

  - name: monitoring-critical-discord
    discord_configs:
      - webhook_url: "__DISCORD_WEBHOOK_MONITORING_CRITICAL__"
        send_resolved: true
        title: >-
          [__ALERT_ENV__][critical] {{ .CommonLabels.alertname }}
        message: >-
          서비스={{ .CommonLabels.service }}
          인스턴스={{ .CommonLabels.instance }}
          상태={{ .Status }}
          요약={{ .CommonAnnotations.summary }}
          상세={{ .CommonAnnotations.description }}

  - name: monitoring-warning-discord
    discord_configs:
      - webhook_url: "__DISCORD_WEBHOOK_MONITORING_WARNING__"
        send_resolved: true
        title: >-
          [__ALERT_ENV__][warning] {{ .CommonLabels.alertname }}
        message: >-
          서비스={{ .CommonLabels.service }}
          인스턴스={{ .CommonLabels.instance }}
          상태={{ .Status }}
          요약={{ .CommonAnnotations.summary }}
          상세={{ .CommonAnnotations.description }}

  - name: payment-discord
    discord_configs:
      - webhook_url: "__DISCORD_WEBHOOK_PAYMENT__"
        send_resolved: true
        title: >-
          [__ALERT_ENV__][payment][{{ .CommonLabels.severity }}] {{ .CommonLabels.alertname }}
        message: >-
          서비스={{ .CommonLabels.service }}
          인스턴스={{ .CommonLabels.instance }}
          상태={{ .Status }}
          요약={{ .CommonAnnotations.summary }}
          상세={{ .CommonAnnotations.description }}
