CREATE TABLE withdrawn_payment_orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    withdrawn_user_id BIGINT NOT NULL,
    withdrawn_account_id BIGINT NULL,
    original_payment_order_id BIGINT NOT NULL,
    original_group_buy_id BIGINT NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    quantity INT NOT NULL,
    product_amount INT NOT NULL,
    fee_amount INT NOT NULL,
    total_amount INT NOT NULL,
    agreed_no_cancel_after_goal BIT(1) NOT NULL,
    agreed_refund_before_goal BIT(1) NOT NULL,
    agreed_no_refund_after_no_show BIT(1) NOT NULL,
    agreed_no_withdrawal BIT(1) NOT NULL,
    status VARCHAR(30) NOT NULL,
    approved_at DATETIME NULL,
    failed_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    withdrawn_at DATETIME NOT NULL,
    retention_expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uidx_withdrawn_payment_orders_original_payment_order_id (original_payment_order_id),
    KEY idx_withdrawn_payment_orders_withdrawn_user_id (withdrawn_user_id),
    KEY idx_withdrawn_payment_orders_withdrawn_account_id (withdrawn_account_id),
    KEY idx_withdrawn_payment_orders_retention_expires_at (retention_expires_at)
);

CREATE TABLE withdrawn_participations (
    id BIGINT NOT NULL AUTO_INCREMENT,
    withdrawn_user_id BIGINT NOT NULL,
    withdrawn_account_id BIGINT NULL,
    original_participation_id BIGINT NOT NULL,
    original_group_buy_id BIGINT NOT NULL,
    original_payment_order_id BIGINT NULL,
    quantity INT NOT NULL,
    product_amount INT NOT NULL,
    fee_amount INT NOT NULL,
    total_amount INT NOT NULL,
    status VARCHAR(30) NOT NULL,
    pickup_status VARCHAR(30) NOT NULL,
    pickup_token VARCHAR(100) NULL,
    picked_up_at DATETIME NULL,
    cancel_reason VARCHAR(50) NULL,
    cancel_reason_detail VARCHAR(500) NULL,
    cancelled_at DATETIME NULL,
    refunded_at DATETIME NULL,
    approved_refund_amount INT NULL,
    owner_refund_review_status VARCHAR(30) NULL,
    owner_refund_dispute_reason VARCHAR(500) NULL,
    owner_refund_reviewed_at DATETIME NULL,
    withdrawn_at DATETIME NOT NULL,
    retention_expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uidx_withdrawn_participations_original_participation_id (original_participation_id),
    KEY idx_withdrawn_participations_withdrawn_user_id (withdrawn_user_id),
    KEY idx_withdrawn_participations_withdrawn_account_id (withdrawn_account_id),
    KEY idx_withdrawn_participations_retention_expires_at (retention_expires_at)
);

CREATE TABLE withdrawn_refund_requests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    withdrawn_user_id BIGINT NOT NULL,
    withdrawn_account_id BIGINT NULL,
    original_refund_request_id BIGINT NOT NULL,
    original_participation_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    requested_amount INT NOT NULL,
    approved_refund_amount INT NULL,
    rejected_reason VARCHAR(200) NULL,
    requested_at DATETIME NOT NULL,
    approved_at DATETIME NULL,
    rejected_at DATETIME NULL,
    refunded_at DATETIME NULL,
    withdrawn_at DATETIME NOT NULL,
    retention_expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uidx_withdrawn_refund_requests_original_refund_request_id (original_refund_request_id),
    KEY idx_withdrawn_refund_requests_withdrawn_user_id (withdrawn_user_id),
    KEY idx_withdrawn_refund_requests_withdrawn_account_id (withdrawn_account_id),
    KEY idx_withdrawn_refund_requests_retention_expires_at (retention_expires_at)
);
