package com.moongchijang.domain.notification.domain.entity

enum class NotificationTriggerType {
    PICKUP_SAME_DAY_MORNING,              // ①
    PICKUP_DAY_BEFORE_MORNING,            // ②
    PICKUP_NOT_COMPLETED_AFTER_CUTOFF,    // ③
    WISH_DEADLINE_MINUS_3_DAYS,           // ④
    WISH_DEADLINE_MINUS_1_DAY,            // ⑤
    WISH_TARGET_ACHIEVED_IMMEDIATE,       // ⑥
    APPLY_PAYMENT_SUCCESS_IMMEDIATE,      // ⑦
    APPLY_GROUPBUY_ACHIEVED_IMMEDIATE,    // ⑧
    APPLY_GROUPBUY_FAILED_IMMEDIATE,      // ⑨
    REQUEST_OPENED_IMMEDIATE,             // ⑩
    REQUEST_REJECTED_IMMEDIATE,           // ⑪
    REQUEST_NEW_PARTICIPANT_IMMEDIATE,    // ⑫
    REQUEST_TARGET_ACHIEVED_IMMEDIATE,    // ⑬
    REQUEST_DEADLINE_MINUS_3_DAYS,        // ⑭
    OWNER_PICKUP_SAME_DAY_MORNING,        // ⑮
    OWNER_PICKUP_DAY_BEFORE_MORNING,      // ⑯
    OWNER_GROUPBUY_ACHIEVED_IMMEDIATE,    // ⑰
    OWNER_GROUPBUY_FAILED_IMMEDIATE,      // ⑱
    OWNER_CLOSE_REQUEST_APPROVED_IMMEDIATE, // ⑲
    OWNER_CLOSE_REQUEST_REJECTED_IMMEDIATE, // ⑳
    OWNER_OPEN_REQUEST_APPROVED_IMMEDIATE, // ㉑
    OWNER_OPEN_REQUEST_REJECTED_IMMEDIATE, // ㉒
    OWNER_ORDER_CONFIRM_REQUIRED_IMMEDIATE, // ㉓
    OWNER_ORDER_CANCELLED_IMMEDIATE       // ㉔
}
